default_platform(:ios)

platform :ios do
  desc "lane: build iOS app without signing and optionally send to Firebase"
  lane :firebase_distribution do
    UI.message("🚀 Starting iOS build")

    sh("flutter clean")

    sh("flutter build ipa --release --no-codesign --export-method ad-hoc --no-tree-shake-icons")


    sh(
      "flutter build ipa " \
      "--release " \
      "--no-codesign " \
      "--export-method ad-hoc " \
      "--no-tree-shake-icons"
    )
    ipa_path = "build/ios/ipa/Runner.ipa"

    unless File.exist?(ipa_path)
      UI.user_error!("❌ IPA not found at #{ipa_path}")
    end

    UI.success("IPA generated")

    
        firebase_app_distribution(
          app: "1:937001601167:ios:005384c7dc9eeda9d8c8fa", 
          testers: "alharbisa24@gmail.com",
          release_notes: "iOS build from GitHub Actions",
          ipa_path: ipa_path,
          firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]
        )
      rescue => e
        UI.error("⚠️ Firebase upload failed (expected for unsigned IPA): #{e.message}")
  end
end
